### ISSUE TITLE
Recent Spam Harvest and Approved comments tabs are missing

### ISSUE THREAD

**Issue by xibe** [strider72/spam-karma#34]
Using version 2.4-alpha-20150612, the only tabs I see are those: General Settings, Blacklist, SK Logs, About.

Tabs that I was used to in v2.3 have seemingly disappear. I thought it was just a question of switching to v2.4 and waiting for spam to happen, but that isn't the case.

**Comment by strider72** [comment]
This was a patch a while back by "if.website". Moved the Karma reporting to the main WP Comments page.

**Comment by xibe** [comment]
Indeed! Missed that patch. Thanks a lot :)

**Comment by xibe** [comment]
Just sad we can't see a given comment's karma points anymore :)

**Comment by strider72** [comment]
You can see the Karma, on the Comments screen.  Mouse over a comment.

**Comment by xibe** [comment]
Did that, a mouseover only display "Not spam | Delete forever", unless I'm missing something.

**Comment by strider72** [comment]
It appears when you mouse over the actual text of the comment.

This is something I'd like to fix, actually. It creates a bad "bouncing" effect if you scroll down, and this large Karma box appears and disappears for each separate comment.  My intent is to show just the Karma Score for each, and clicking on that (not mouseover) shows the details.

See issue #20
